flusova.sofia/HW1
polis-vk/java-tasks pull request #1182
Opened 2023-03-04 18:25 UTC by Bazhenator

2023-03-06 11:39 UTC, Bazhenator commented
maxNumber не проходит тесты, т.к., они были по дефолту закомменчены. Не заметила сразу.

2023-03-06 17:04 UTC, Bazhenator commented
upd: исправлено.

2023-03-06 19:37 UTC, shakirov-aa requested changes

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
>          return x1 + ", " + x2;
тут тернарным оператором, может?

return x1 >= x2 ? x1 + ", " + x2 : x2 + ", " + x1;

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double dist = Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
можно заинлайнить?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double i = a, sum = 0.0;
в одну строку объявлять переменные не очень

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double i = a, sum = 0.0;
вместо 0.0 можно просто 0

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double i = a, sum = 0.0;
для "i" можно более говорящее название?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return sum;
перед return неплохо пустую строку оставить, чтобы разделять логику вычисления и возврат ответа

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long tempA = Math.abs(a);
Это не сработает для кейса, когда a = Long.MIN_VALUE

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte size = (byte) (Math.log10(a) + 1);
можно без логарифма?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        for (byte curIndex = 1; curIndex < size + 1; ++curIndex, --grad) {
условие цикла сложное, можно проще

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return y1 + (double)((y2 - y1) * (x3 - x1)) / (double)(x2 - x1);
форматирование?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double module_d2 = Math.sqrt(Math.pow(x4 - x2, 2) + Math.pow(y4 - y2, 2));
в Java не принято называть переменные с нижним подчеркиванием, оно используется только для static final переменных

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            return 0.0;
просто 0?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        } else {
else не нужен и в целом if лучше инвертировать, чтобы проще воспринималось:

```
        if (module_d2 == 0 || module_d1 == 0) {
            return 0;
        }

        double cosAlfa = Math.abs((x3 - x1) * (x4 - x2) + (y3 - y1) * (y4 - y2)) / (module_d1 * module_d2); //using cosAlfa = |v_A * v_B| / (m_A * m_B)
        double sinAlfa = Math.sqrt(1 - Math.pow(cosAlfa, 2));

        return 0.5 * module_d1 * module_d2 * sinAlfa;
```

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i < n + 1; ++i) {
циклы принято писать от 0

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
>      public static int sum(int n) {
можно по формуле?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        } else if (bottom >= top) {
можно без else if?

просто два отдельных if-а, в них же return

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        {
открывающую фигурную скобку пишут на той же строки, что и while

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            n /= 10;
входные параметры не меняем

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +               return Math.abs(curNum);
тут отступ неправильный

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
>      public static int kDecimal(int n, int order) {
можно с помощью степеней и без цикла?

2023-03-06 19:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i < n + 1; ++i) {
обычно пишут i++

2023-03-06 19:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +                maxDigit = (int) (tempA / Math.pow(10, grad));
тут это вычисление "tempA / Math.pow(10, grad)" уже третий раз подряд

2023-03-09 17:54 UTC, shakirov-aa requested changes

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double tempA = a;
название не очень говорящее)
и можно было через цикл for?

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        for (byte curIndex = 1; curIndex < size + 1; ++curIndex, --grad) {
> условие цикла сложное, можно проще

up

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +                if (curDigit == 9) {
зачем внутри другого if-a? можно же перед

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return y1 + (double) ((y2 - y1) * (x3 - x1)) / (double) (x2 - x1);
можно одним преобразованием обойтись?

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return (top - bottom > 0 ? ((height - bottom - 1) / (top - bottom)) + 1 : Integer.MAX_VALUE);
тут слишком большой тернарный оператор получается, я бы разбил на if-ы

2023-03-09 17:54 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        int tempN = n;
зачем? нигде же не изменяется

2023-03-10 22:33 UTC, Bazhenator commented
@shakirov-aa , добрая ночь! постаралась максимально учесть все недочеты и исправить их. Преинкримент и предекремент убрала.

2023-03-14 07:07 UTC, shakirov-aa requested changes

2023-03-14 07:07 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        for (byte grad = (byte) (size - 1); grad != -1; --grad) {
grad >= 0 было бы лучше

2023-03-14 07:07 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double maxDigit = 0;
maxDigit дробное число?

2023-03-14 07:07 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
>      public static byte maxNumber(long a) {
если передать 889, то неправильно отработает функция

2023-03-18 11:34 UTC, shakirov-aa commented
Нет исправлений с последней проверки :(
8 из 11 тугриков

2023-03-18 11:34 UTC, closed without merging