nedorezov.danil/hw1
polis-vk/java-tasks pull request #1183
Opened 2023-03-04 19:34 UTC by DinozavrrrDan

2023-03-06 19:59 UTC, shakirov-aa requested changes

2023-03-06 19:59 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double integralSum = 0.0;
можно просто 0?

2023-03-06 19:59 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
>      public static byte maxNumber(long a) {
тут имеет смысл идти с начала и учитывать кейс, что если встретили цифру 9, то досрочный выход из цикла

2023-03-06 19:59 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            maxNumber = Math.max(maxNumber, currentNumber);
на строке выше уже определили большее число

2023-03-06 19:59 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return y1 + ((y2 - y1) * 1.0 / (x2 - x1)) * (x3 - x1);
умножать на 1 мало смысла

2023-03-09 17:55 UTC, shakirov-aa commented
Нет изменений, проверка пропущена :(

2023-03-09 18:16 UTC, DinozavrrrDan commented
> Нет изменений, проверка пропущена :(

Только выгрузил изменения( Unlucky

2023-03-14 07:57 UTC, shakirov-aa requested changes

2023-03-14 07:57 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int length = (int) (Math.abs(Math.log10(number)) + 1);
можно без модуля

2023-03-14 07:57 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +                if (currentDigit == 9) {
этот if можно выше вынести?

2023-03-14 07:57 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i != order; i++) {
не исправлено - лучше while

2023-03-14 09:00 UTC, DinozavrrrDan commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +                if (currentDigit == 9) {
Вынес if

2023-03-14 09:00 UTC, DinozavrrrDan commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int length = (int) (Math.abs(Math.log10(number)) + 1);
Убрал

2023-03-18 11:39 UTC, shakirov-aa commented
11 из 11 тугриков

2023-03-18 11:39 UTC, closed without merging