Homework 1
polis-vk/java-tasks pull request #1184
Opened 2023-03-04 20:27 UTC by ThreeAi

solution all tasks

2023-03-06 19:59 UTC, VladislavFetisov requested changes

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
>          double x2 = 0;
зачем инициализировать нулем

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        return (float)Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
не забывайте нажимать ctrl+alt+l, чтобы форматирование везде норм было

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        do{
форматирование

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/MainTask.java
> +    private static void main(String args) {
Кажется что нужен другой модификатор доступа

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        else{
else после return

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        else{
Форматирование

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return Math.abs((n / (int)Math.pow(10, --order)) % 10);
форматирование

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return Math.abs((n / (int)Math.pow(10, --order)) % 10);
Изменение входного параметра

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        else{
else после return

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            return (int)Math.ceil((float)((height - top) / (float)(top - bottom))) + 1;
Форматирование

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        else
else после return

2023-03-06 19:59 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        {
скобочка на той же строке что и while

2023-03-07 05:09 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long input = a;
а input нельзя сразу abs сделать? Зачем он дальше?

2023-03-07 05:10 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            res = y1 - ((double) ((x1 - x3) * (y1 - y2)) / (x1 - x2));   //вывод формулы из равенста отношений (x1 - x3) / (x1 - x2) = (y1 -y3) / (y1 - y2)
отдавайте сразу, так проще читать будет

2023-03-07 05:10 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            res = 1;
отдавайте сразу

2023-03-07 05:10 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            res = 1;
отдавайте сразу

2023-03-07 05:11 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        int temp = n;
в этом случае не нужен temp: a/2 не изменяет a

2023-03-07 05:12 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        int temp = n;
a/=2 изменяет

2023-03-07 05:14 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        do {
и зачем цикл с постусловием?

2023-03-07 07:17 UTC, ThreeAi commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        do {
для случае если входное значение 0, чтобы count (количество цифр) прибавило 1

2023-03-10 20:50 UTC, VladislavFetisov requested changes

2023-03-10 20:50 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            if (input % 10 >= maxDigit || input % 10 <= -maxDigit) {
да, ошибся, тогда здесь abs все таки используйте, но  и дальше переиспользуйте этот найденный модуль, когда в maxDigit присваивание будете делать

2023-03-10 20:50 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            if (input % 10 >= maxDigit || input % 10 <= -maxDigit) {
ищем максимальную цифру слева направа - если первая цифра в числе 9
например, 91244124124
то нет смысла обходить остальные цифры 1244124124

в вашей реализации мы идем справа налево

2023-03-10 20:50 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        } else if (bottom >= top) {
else после return

2023-03-10 20:50 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/MainTask.java
> +    public static void main(String args) {
чего-то не хвататет, одиночную строку явно args не назвали бы

2023-03-18 10:10 UTC, VladislavFetisov approved these changes
Полный балл

2023-03-18 10:12 UTC, closed without merging