Выполнены DoubleTask, HomeworkTask, IntegerTask. MainTask находится в разработке
polis-vk/java-tasks pull request #1186
Opened 2023-03-05 08:19 UTC by YanaSpirchina

Выполнила все задания, кроме MainTask. Пока закомментировала своё решение. Подскажите, пожалуйста, я могу изменять метод(в MainTask) private static main(String args){}. Я могу добавить void? Тем самым получить -> private static void main(String args){}

2023-03-06 20:02 UTC, shakirov-aa commented
> Выполнила все задания, кроме MainTask. Пока закомментировала своё решение. Подскажите, пожалуйста, я могу изменять метод(в MainTask) private static main(String args){}. Я могу добавить void? Тем самым получить -> private static void main(String args){}

Да, можно менять сигнатуру метода в этом задании

2023-03-06 20:10 UTC, shakirov-aa requested changes

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
>          double x1 = 0;
лучше объявить сразу при присваивании

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double countRectangle = Math.abs(b - a) / delta;
можно без этого

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int length = String.valueOf(a).length();
нельзя на строках

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            sin = 1;
в обоих случаях sin = 1;
может тогда в первый if добавить условие второго if-a? через "||"

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
>      public static int sum(int n) {
можно по формуле?

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        } else if (top <= bottom) {
можно без else, а просто отдельным if-ом, тк внутри if-ов ретурны

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (place < height) {
тут "воспроизводим" движение гусеницы, но можно же по формуле посчитать?

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            n /= 10;
входные параметры не меняем

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (order != 0) {
лучше с начала идти и добавить досрочный выход, если встретили "9"

2023-03-06 20:10 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return n * factorial((byte) (n - 1));
Какое максимальное количество вызовов метода будет давать правильный ответ, если использовать рекурсию?

2023-03-07 18:33 UTC, YanaSpirchina commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (order != 0) {
Скажите, пожалуйста, что означает "9"? Не совсем поняла суть алгоритма. И не могли бы, пожалуйста, подсказать, как делать обход с начала и чем он выигрывает у обхода с конца?

2023-03-09 18:16 UTC, shakirov-aa requested changes

2023-03-09 18:16 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int length = Math.abs((int) (Math.log10(Math.abs(a)) + 1));
тут один модуль лишний

2023-03-09 18:16 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte count = 1; //счётчик цифры
можно без этой переменной

2023-03-09 18:16 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (count != 0) {
можно просто через степень и без цикла?

2023-03-09 18:16 UTC, shakirov-aa commented on src/test/java/ru/mail/polis/homework/simple/HomeworkTaskTest.java
> -//        assertEquals(1, HomeworkTask.maxNumber(Long.MIN_VALUE));
не должно быть файлов тестов в PR-е, домашка не будет засчитана, если не убрать

2023-03-10 18:48 UTC, YanaSpirchina commented
Закрыла PR, тк были удалены некоторые файлы и была нарушены структура проекта. Создала новый PR "Homework1 Spirchina Yana"

2023-03-10 18:48 UTC, closed without merging