Chupina.anna/HW1
polis-vk/java-tasks pull request #1187
Opened 2023-03-05 08:56 UTC by Aneynni

2023-03-06 20:22 UTC, shakirov-aa requested changes

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double x1, x2, D;
в одну строку объявлять не очень, чаще всего лучше объявлять в том месте, где используется

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        min = (x1 < x2 ? x1 : x2);
очень странно, что мы два раза сравниваем x1 и x2;
да и в целом можно обойтись без max и min

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +    {
открывающая фигурная скобка пишется на одной строке с сигнатурой метода

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double distanceBetweenPoints;
1) лучше было объявить на той же строке, где присваиваем
2) вообще можно не объявлять в данном случае, а сразу возвращать результат вычисления

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +    {
открывающая фигурная скобка пишется на одной строке с сигнатурой метода (во всех остальных местах тоже)

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        i = (byte)(num == 0 ? 1 : 0);
форматирование

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +                maxDecimal = (byte)(Math.abs(num) % 10);
форматирование

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return (byte)( i - maxNumber );
форматирование

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +    public static byte maxNumber(long a)
тут лучше с начала идти и добавить досрочный выход, если встретили "9"

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double k, b, y3;
в одну строку не объявляем

2023-03-06 20:22 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        k = (double)(y2 - y1) / (x2 - x1);
форматирование

2023-03-06 20:29 UTC, VladislavFetisov requested changes

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        return (float)distanceBetweenPoints;
моожно заинлайнить и форматирование ужасное

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (byte i = 1; i <= n; i++) {
можно и с 2 начать)

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        numToOrder = Math.abs(n) / (int)Math.pow(10, order - 1);
заинлайнить и форматирование

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double x1, x2, D;
Заинлайнивайте везде где можно обьявления, типо не 
int a;
a=1;
Лучше: int a=1;

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        return (float)distanceBetweenPoints;
ctrl+alt+l, надеюсь вы в idea работаете

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        distanceBetweenPoints = Math.sqrt( (Math.pow(( x2 - x1 ), 2)) + Math.pow(( y2 - y1 ), 2) );
ctrl+alt+l, надеюсь вы в idea работаете

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double S1, S2;
заинлайнить

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double S1, S2;
И обьявления на разных строчках

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double k, b, y3;
И обьявления на разных строчках

2023-03-06 20:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        max = (x1 > x2 ? x1 : x2);
достаточно одного ифа, чтобы понять что макс а что мин

2023-03-09 18:23 UTC, shakirov-aa requested changes

2023-03-09 18:23 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte orders = (byte) ((int) (Math.log10(a)) + 1);
orders -> digitsCount?

2023-03-09 18:23 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte maxDecimal = 0;
maxDigit?

2023-03-09 18:23 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte maxOrder = orders;
maxDigitPosition?

2023-03-14 08:02 UTC, shakirov-aa requested changes

2023-03-14 08:02 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        //площадь как сумма двух треугольников
после // ставят пробел обычно

2023-03-14 10:18 UTC, Aneynni commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte maxDigitPosition = digitsCount;
осознала

2023-03-18 11:42 UTC, shakirov-aa commented
11 из 11 тугриков

2023-03-18 11:42 UTC, closed without merging