домашняя работа 1 Панфилов Фёдор
polis-vk/java-tasks pull request #1194
Opened 2023-03-05 16:34 UTC by iamboneidle

Панфилов

2023-03-06 20:51 UTC, VladislavFetisov requested changes

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        } else {
else после return

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            sqr = sqr + delta * function.applyAsDouble(a);
используйте +=

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            a = a / 10;
изменять входные параметры нельзя

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            k = k + 1;
++

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int qtt = (int) Math.log10(a) + 1;
можно исбежать qtt, посмотрим на k

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return n * (n + 1) / 2;
круто

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if (top == bottom || top < bottom){
можно обеденить в одно условие

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            fact = fact * i;
*=

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (a < height){
нужно сделать без цикла

2023-03-06 20:51 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +
строчка не нужна

2023-03-10 20:34 UTC, VladislavFetisov requested changes

2023-03-10 20:35 UTC, VladislavFetisov commented
Исправлять будете?

2023-03-11 10:42 UTC, iamboneidle commented
> Исправлять будете?

да

2023-03-13 20:07 UTC, VladislavFetisov requested changes

2023-03-13 20:07 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        for (; a < b; a = a + delta) {
осталось

2023-03-13 20:07 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int qtt = (int) Math.log10(h) + 1;
ищем максимальную цифру слева направа - если первая цифра в числе 9
например, 91244124124
то нет смысла обходить остальные цифры 1244124124

в вашей реализации мы идем справа налево

2023-03-13 20:07 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int qtt = (int) Math.log10(h) + 1;
Попробуйте выбрать названия переменных, которые будут понятны другим людям

2023-03-18 10:42 UTC, VladislavFetisov approved these changes
Не сделано MainTask и маленькие памарки, поэтому 8.5 из 10

2023-03-18 10:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double i = a;
i используется для индекса

2023-03-18 10:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            sqr += delta * function.applyAsDouble(i);
причем тут sqr

2023-03-18 10:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double quantityOfDigits = Math.ceil(Math.log10((double) num));
переменную стоило сделать int

2023-03-18 10:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +    public static void main(String[] args){
это зачем здесь

2023-03-18 10:44 UTC, closed without merging