pelipeychenko.denis/hw1
polis-vk/java-tasks pull request #1195
Opened 2023-03-05 20:42 UTC by LioShady

2023-03-06 11:29 UTC, LioShady commented
MaxNumber не проходит все тесты

2023-03-07 04:54 UTC, VladislavFetisov requested changes

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double x1 = (-b + Math.sqrt(discriminant)) / (2 * a);
два раза вычиляем корень

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long numberLength = (long) Math.pow(10, String.valueOf(a).length() - 1);
Выглядит очень плохо

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i <= n; i++) {
умножение на 1 что-нибудь дает?

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return (int) Math.abs(n / Math.pow(10, order - 1) % 10);
не понятен порядок операций, расставьте скобки

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (currentLevel < height - top) {
а можно без цикла?

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 0; i <= n; i++) {
можете посмотреть про арифметическую прогрессию

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            if (a / numberLength % 10 > maxDigit) {
введите дополнительную переменную, не очень читается

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double sumX = x1 * y2 + x2 * y3 + x3 * y4 + x4 * y1;
почему sumX?

2023-03-07 04:54 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return vectorY21 * factor + y1;
А из какой формулы это выведено?

2023-03-10 20:33 UTC, VladislavFetisov commented
Исправлять будете?

2023-03-10 21:13 UTC, LioShady commented
> Исправлять будете?

Да, на выходных

2023-03-12 23:41 UTC, LioShady commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long numberLength = (long) Math.pow(10, String.valueOf(a).length() - 1);
Исправил, надеюсь, что так лучше

2023-03-12 23:47 UTC, LioShady commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double sumX = x1 * y2 + x2 * y3 + x3 * y4 + x4 * y1;
Очень условное обозначение, что координаты точек по иксу условной первой фигуры перемножаются на координаты по игрику второй. Но объяснить, почему какая-то фигура первая, а какая-то вторая, сложновато, тем более в тестах они точки задаются где-то по часовой, а где-то против, поэтому такое обозначение наверно реально смысла мало имеет... Исправил, хотя первая и вторая сумма не сильно далеко ушли

2023-03-12 23:51 UTC, LioShady commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return vectorY21 * factor + y1;
Просто векторная алгебра, как-то не задумывался, когда писал. Наверно, выведено из возможности разложить вектор по проекциям и идеи, что 2 коллинеарных вектора можно представить как vector1 = k * vector2

2023-03-13 20:24 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long numberLength = (long) Math.pow(10, (int) (Math.log10(a)));
![изображение](https://user-images.githubusercontent.com/55449507/224822520-e7e520fa-1d01-4b5b-8ce0-f84311a0a256.png)

2023-03-13 20:24 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return vectorY21 * factor + y1;
окей

2023-03-13 20:25 UTC, VladislavFetisov commented
Отлично, максимальный балл

2023-03-13 20:25 UTC, VladislavFetisov approved these changes
Сам закрою пр

2023-03-13 20:27 UTC, LioShady commented
> Отлично, максимальный балл

Благодарю!

2023-03-18 10:47 UTC, closed without merging