First homework done
polis-vk/java-tasks pull request #1196
Opened 2023-03-05 23:41 UTC by polainam

Мезенцева

2023-03-07 05:06 UTC, VladislavFetisov requested changes

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte numberMaxVal = 0;
это индекс

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            if (Math.abs(a % 10) >= MaxVal) {
модуль на каждом шаге?

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +    public static int sum(int n) {
можно еще арифметической прогрессией

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (step < height) {
можно без цикла?

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (order != 0) {
можно без цикла, а со степенями?

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if ((n == 0) || (n == 1)) {
можно в 1 условие?

2023-03-07 05:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/MainTask.java
> -package ru.mail.polis.homework.simple;
опять же

2023-03-09 16:24 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> -package ru.mail.polis.homework.simple;
Исправила

2023-03-09 16:25 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            a /= 10;
Исправила введением переменной copyA

2023-03-09 16:25 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte MaxVal = 0;
Изменила на  maxVal

2023-03-09 16:26 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte numberMaxVal = 0;
Изменила на indexMaxVal

2023-03-09 16:27 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            if (Math.abs(a % 10) >= MaxVal) {
Изменила решение, разделив логику метода для отрицательного и положительного входного числа

2023-03-09 16:28 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (step < height) {
Изменила

2023-03-09 16:28 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        while (order != 0) {
Исправила решение

2023-03-09 16:29 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if ((n == 0) || (n == 1)) {
Исправила на n <= 1, т.к. факториала для отрицательных чисел все равно не существует

2023-03-10 20:30 UTC, VladislavFetisov requested changes

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double squareRoot = Math.sqrt(Math.pow(b, 2) - 4 * a * c);
лучше просто dSquare или discriminantSquare

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double x2 = ((-b + squareRoot) / (2 * a)) + ((-b - squareRoot) / (2 * a)) - x1;
слишком сложно, могла бы вычислить корни, а потом бы просто через if сравнить и вывести

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        for (double i = a; i < b; i += delta) {
i обычно для индекса, здесь явно не индекс

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        if (copyA <= 0) {
все же я неправильно сказал, что модуль на каждом шаге нельзя-можно, прошлое решение было ближе, но:

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        if (copyA <= 0) {
ищем максимальную цифру слева направа - если первая цифра в числе 9
например, 91244124124
то нет смысла обходить остальные цифры 1244124124

в вашей реализации мы идем справа налево

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i <= n; i++) {
можно было бы через арифметическую прогрессию

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if (n < 0) {
не думаю, что это нужно, просто можно вывести abs)

2023-03-10 20:30 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if (n <= 1) {
почти, но чем рекурсия при n=0 отличает от n=1? Вроде как ничем, может дать ей работать до 0?

2023-03-12 13:43 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        if (copyA <= 0) {
Изменила реализацию

2023-03-12 13:44 UTC, polainam commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 1; i <= n; i++) {
Исправилась

2023-03-13 20:31 UTC, VladislavFetisov requested changes

2023-03-18 10:49 UTC, VladislavFetisov approved these changes
9.5 из 10

2023-03-18 10:49 UTC, closed without merging