rassokhina-veronika-hw1
polis-vk/java-tasks pull request #1198
Opened 2023-03-06 09:10 UTC by nikaNGC224

Сделала всё, кроме HomeworkTask

2023-03-07 12:44 UTC, Nekobitlz requested changes

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +            x2 = (-b + sqrtD) / (2 * a);
одинаковый код, можно вынести в отдельную функцию

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        return (float) length;
можно заинлайнить:
```
return (float) Math.sqrt(height * height + width * width);
```

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double length = Math.sqrt(height * height + width * width);
Вообще по идее [разницы нет по перформансу для квадрата](https://stackoverflow.com/a/29146005/11877973), но для степени удобнее использовать Math.pow

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        if ((top < height) && (top <= bottom)) {
лишние скобки

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        int i;
вместо i лучше использовать более человекочитаемое название

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            if ((top * i - bottom * (i - 1)) >= height) {
лишние скобки

2023-03-07 12:44 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (long i = 2; i <= (long) n; ++i) {
зачем тут кастить к лонгу обе переменных? `n` - byte, то есть не может быть больше 127, так же как и `i`, нет смысла использовать под это больше памяти

2023-03-07 20:34 UTC, nikaNGC224 commented
Все сделано

2023-03-11 01:02 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        if ((yArray[2] < yArray[3]) & (yArray[1] > yArray[2])) {
В ифах лучше использовать сокращенные операторы: && ||, они прервутся, если первое условие не выполнится

2023-03-11 01:02 UTC, Nekobitlz commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        if ((yArray[2] < yArray[3]) & (yArray[1] > yArray[2])) {
и скобки еще лишние тут убрать надо

2023-03-15 13:10 UTC, Nekobitlz commented
Принято

2023-03-15 13:10 UTC, closed without merging