Kashirin Kirill HW1
polis-vk/java-tasks pull request #1209
Opened 2023-03-08 14:11 UTC by theusick

Каширин Кирилл

2023-03-10 19:50 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte currentDigit = (byte) (number % 10);
Не нужно находить это до цикла

2023-03-10 20:06 UTC, VladislavFetisov requested changes

2023-03-10 20:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        for (int i = 0; i < order - 1; i++) {
можно сделать без чикла с помощью степеней?

2023-03-10 20:08 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        byte currentDigit = (byte) (number % 10);
ищем максимальную цифру слева направа - если первая цифра в числе 9
например, 91244124124
то нет смысла обходить остальные цифры 1244124124

в вашей реализации мы идем справа налево

2023-03-10 20:08 UTC, VladislavFetisov commented
А так довольно неплохо для 1 попытки

2023-03-13 19:48 UTC, VladislavFetisov requested changes

2023-03-13 19:48 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        final byte maxPossibleDigit = 9;
зачем здесь final

2023-03-13 19:48 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            currentDigit = (byte) (a / Math.pow(10, numberLength - i) % 10);
на каждом шаге возводим в степень? слишком затратно получается, можно проще?

2023-03-13 21:19 UTC, theusick commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        final byte maxPossibleDigit = 9;
Дабы показать, что переменная в последующем коде не изменяется. Использовалась она только в строке с проверкой максимального значения на соответствие ей:
https://github.com/polis-vk/java-tasks/blob/7e4013f04d6973c2145071dde797dc2045ea7acd/src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java#L37
Убрал ее за ненадобностью, так как magic numbers в виде тех же `10` сохранялись в коде

2023-03-18 10:58 UTC, VladislavFetisov approved these changes
Полный балл

2023-03-18 10:58 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            currentDigit = (byte) (a / numberOrder % 10);
не хватает скобок для порядка операций

2023-03-18 10:58 UTC, closed without merging