Карасев Вячеслав, домашнее задание №1
polis-vk/java-tasks pull request #1212
Opened 2023-03-09 11:06 UTC by slavikfish03

Выполнены все задания + дополнительное задание в HomeworkTask. Все тесты пройдены успешно.

2023-03-10 20:16 UTC, VladislavFetisov requested changes

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        } else {
else после return

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int j = 1;  // номер текущей цифры и в конце while'а - кол-во цифр в числе
зачем комменты-назовите нормально и понятно будет

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        while (a != 0) {
ищем максимальную цифру слева направа - если первая цифра в числе 9
например, 91244124124
то нет смысла обходить остальные цифры 1244124124

в вашей реализации мы идем справа налево

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return (y1 + (y2 - y1) * (double)(x3 - x1) / (double)(x2 - x1));
зачем два раза кастовать к double

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double AreaABC, AreaACD; // площади ABC и ACD
обьявляем на разных строчках, из названия переменных и так понятно что это, называем с маленькой буквы(camel case)

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        return (int)(Math.ceil((double)(height - top) / (top - bottom)) + 1);
форматирование, не забывает нажимать ctrl+alt+l

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            n = n / 10;
менять входные параметры нельзя, используйте /= вместо  = .. /

2023-03-10 20:16 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +            n = n / 10;
стоит сделать без цикла с помощью степеней

2023-03-10 20:53 UTC, slavikfish03 commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        return (y1 + (y2 - y1) * (double)(x3 - x1) / (double)(x2 - x1));
Там целочисленное деление, и если скастовать double ко всей дроби, то получается иной результат (не тот который я хочу), чем если к числителю и знаменателю отдельно, поэтому я сделал так. Как лучше тогда сделать?

2023-03-13 20:39 UTC, VladislavFetisov requested changes

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +        double D = b * b - 4 * a * c;
с маленькой

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/DoubleTask.java
> +            x1 = (-b + Math.sqrt(D)) / (2 * a);
два раза находим корень

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            int digit = (int) (num / Math.pow(10, len - i));
дорого на каждом шаге находить степень

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            num %= Math.pow(10, len - i);
?

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/IntegerTask.java
> +        num /= Math.pow(10, order - 1);
почему просто не инициализировать num как n/Math.pow(10, order - 1);?

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double areaABC;
почему сразу не инициализировать?

2023-03-13 20:39 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        double areaABC;
58 и 60 строчку обьединить, также с 59 и 61

2023-03-18 11:05 UTC, VladislavFetisov approved these changes
Не сделано MainTask и маленькие памарки, поэтому 9 из 10

2023-03-18 11:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        int len = (int) (Math.ceil(Math.log10(num)));
здесь не нужен ceil, int и так к нижней границе кастанет

2023-03-18 11:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +            int digit = (int) (num / positionCounter);
вообще byte по идее можно

2023-03-18 11:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/simple/HomeworkTask.java
> +        long positionCounter = (long) (Math.pow(10, len - 1)); // переменная для получения первой цифры числа
вообще это не counter получается

2023-03-18 11:06 UTC, closed without merging