Homework2 - Хайбуллин
polis-vk/java-tasks pull request #1223
Opened 2023-03-11 22:53 UTC by xayblln

Все задания решены

2023-03-14 10:14 UTC, VladislavFetisov requested changes

2023-03-14 10:14 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                    value = Double.valueOf(copiedStr);
лучше сразу return

2023-03-14 10:14 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                    if (counter == str.length() - 1) {
очень плохо, а если я вставлю тест "ea", который просто отодвинул e на 1 влево, это говорит о том, что вы не придумали алгоритм, а просто подогнали все под тесты, попробуйте разделить логику на то, что может быть перед "e" и на то, что может быть после "e"

2023-03-18 07:52 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                    if (counter == str.length() - 1) {
Фиксить будете?

2023-03-18 07:53 UTC, VladislavFetisov commented
Фиксить будете?

2023-03-18 18:50 UTC, xayblln commented
Да, попробую18.03.2023, 12:53, "Vladislav" ***@***.***>:
Фиксить будете?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-20 16:53 UTC, VladislavFetisov requested changes

2023-03-20 16:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +//            for (int arrayMaxCounter = 0; arrayMaxCounter < arrayMax.length; arrayMaxCounter++) {
вам не обязательно пушить все изменения

2023-03-26 20:42 UTC, VladislavFetisov approved these changes

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            arrayMax = reverse(arrayMax);
Так делать точно не нужно, в Arrays.sort есть метод с компаратором

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
Неплохо, 3 тугрика

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
4 тугрика

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Long.valueOf(result) > (long) Integer.MAX_VALUE || Long.valueOf(result) < (long) Integer.MIN_VALUE) {
зачем 3 раза делать valueOf

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Long.valueOf(result) > (long) Integer.MAX_VALUE || Long.valueOf(result) < (long) Integer.MIN_VALUE) {
не обязательно кастить к лонгу

2023-03-26 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
5 тугриков

2023-03-26 20:43 UTC, VladislavFetisov commented
Итого 12 тугриков

2023-03-26 20:45 UTC, closed without merging