Homework2 Spirchina Yana
polis-vk/java-tasks pull request #1228
Opened 2023-03-12 12:36 UTC by YanaSpirchina

…e passed

2023-03-14 09:49 UTC, shakirov-aa requested changes

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        Pair[] arrayOfPair = new Pair[str.length()];
можно не сохранять все пары, а только максимальное?

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
можно добавить досрочный выход, если очевидно, что большее значение уже не встретим?

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +            if (arrayOfPair[i] != null && maxCountOfRepetition < (int) arrayOfPair[i].getSecond()) {
тут проверяем на null, потому что выделили память, которая в итоге не понадобилась

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        StringBuilder newStr = new StringBuilder();
newStr -> sb?

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (!Character.isDigit(arrayOfStr[i])) {
то что внутри for-а можно упростить так:

```
            if (Character.isDigit(arrayOfStr[i])) {
                newStr.append(str.charAt(i));
                continue;
            }

            if (arrayOfStr[i] == 'e') {
                if (countE > 1 || i == str.length() - 1) {
                    return null;
                }
                newStr.append(str.charAt(i));
                countE++;
                continue;
            }

            if (arrayOfStr[i] == '.') {
                if (countDots > 1) {
                    return null;
                }
                newStr.append(str.charAt(i));
                countDots++;
                continue;
            }

            if (arrayOfStr[i] == '-') {
                if (newStr.length() == 0 || newStr.charAt(newStr.length() - 1) == 'e') {
                    newStr.append(str.charAt(i));
                    continue;
                }
                return null;
            }
```

2023-03-14 09:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else if (Integer.MIN_VALUE > Long.valueOf(newStr.toString()) ||
можно просто отдельным if-ом?

2023-03-17 11:30 UTC, YanaSpirchina commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
Скажите, пожалуйста, когда мы в нескольких строках вычисляем длину массива или строки: str.length(), array.length; Нужно ли выносить их в отдельную переменную?

2023-03-18 09:56 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
Необязательно, они работают за O(1)

2023-03-18 10:26 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
Можно за N * log(N)

2023-03-18 10:26 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                if (maxValue <= array[i]) {
N * log(N)

2023-03-18 10:43 UTC, shakirov-aa requested changes

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +import java.util.Arrays;
unused imports

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +                if (str.charAt(i) == str.charAt(i + 1)) {
можно это условие в верхний if вынести?

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +            if (i != str.length() - 1) {
можно после цикла просто ещё раз проверить?

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        for (int i = 0; i <= str.length() - 1; i++) {
тут можно было бы с единицы пойти

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        int countDots = 1;
Можно было boolean для countE и countDots? они же больше одного раза не могут быть.
И странно, что по дефолту 1

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                Long.valueOf(sb.toString()) > Integer.MAX_VALUE) {
тут и на строке выше можно было parseLong?

2023-03-18 10:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            return Long.valueOf(sb.toString());
странно, что уже третий раз вызываем valueOf

2023-03-18 12:00 UTC, YanaSpirchina commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                Long.valueOf(sb.toString()) > Integer.MAX_VALUE) {
Скажите, пожалуйста, чем parseLong лучше будет чем valueOf? И нужно ли тогда везде заменить valueOf на parse?

2023-03-20 15:29 UTC, shakirov-aa requested changes

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +import java.util.Collection;
коллекции не используем

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +import java.sql.Array;
unused импорт

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            maxArray[i] = array[i];
System.arraycopy?

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        Arrays.sort(maxArray, Collections.reverseOrder());
встроенную сортировку не используем, только самописную

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                        //сдвиг элементов вправо
сдвиг можно через System.arraycopy

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        //бинарный поиск
бинарный поиск лучше в отдельный метод вынести?
и реализация не очевидная, есть более стандартный подход к этому - через левую/правую границу

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            returnArray[i] = maxArray[i];
System.arraycopy?

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        for (int i = 0; i < count; i++) {
зачем вообще в новый массив копировать?

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        char symbol = '\0';
почему сюда не присвоить первый символ строки?

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        boolean countE = true;
почему название count, если переменная boolean?
странно, что по умолчанию true - изначальное же нет E или точки

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        return Integer.valueOf(sb.toString());
return (int) number;

2023-03-20 15:29 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                number > Integer.MAX_VALUE) {
Тут незачем переносить, лучше вернуть на строку выше

2023-03-26 14:31 UTC, shakirov-aa commented
14 из 14 тугриков

2023-03-26 14:31 UTC, closed without merging