Homework 2 Alexandrov Artem
polis-vk/java-tasks pull request #1230
Opened 2023-03-12 13:25 UTC by ThreeAi

2023-03-14 21:21 UTC, shakirov-aa requested changes

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +            for (int j = i + 1; j < input.length(); j++) {
код этого цикла можно упростить?

```
                if (input.charAt(j) == c) {
                    count++;
                    continue;
                }

                if (count > maxCount) {
                    maxCount = count;
                    maxChar = c;
                }

                break;
```

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        String input = str + " ";
можно без этого

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
можно добавить досрочный выход, если очевидно, что лучшего варианта уже не найдём

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            } else if (c == 'e') {
можно все эти else if упростить - переделать в обычные if-ы

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            Long temp = Long.valueOf(res.toString());
можно примитив? и parseLong?

2023-03-14 21:21 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (res.charAt(res.length() - 1) == 'e') {
этот кейс могли выше обработать? а то получается какая-то исключительная ситуация - неочевидно для понимания

2023-03-14 21:48 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +            for (int j = i + 1; j < input.length(); j++) {
ещё можно совсем без этого цикла)

2023-03-17 15:00 UTC, ThreeAi commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (res.charAt(res.length() - 1) == 'e') {
это же исключительная ситуация когда в результативной строке последний символ 'e' например 1.3е, добавил еще обработку когда последний символ '-' например 1.3е-

2023-03-18 10:46 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
поправочка: N * log(N)

2023-03-18 10:52 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());
не используем PriorityQueue и Collections

2023-03-18 10:52 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        int countE = 0;
тут и на строке выше можно boolean?

2023-03-18 10:52 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                if (res.length() == 0 && !isNegative) {
если длина 0, то зачем дальше проверять на isNegative?

2023-03-18 10:52 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (res.charAt(res.length() - 1) == 'e') {
а почему выше не обработать, там где добавляли минус и e, что это не последний символ?

2023-03-18 10:53 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (res.charAt(res.length() - 1) == 'e') {
> это же исключительная ситуация когда в результативной строке последний символ 'e' например 1.3е, добавил еще обработку когда последний символ '-' например 1.3е-

а почему выше не обработать, там где добавляли минус и e, что это не последний символ?

2023-03-18 22:59 UTC, ThreeAi commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (res.charAt(res.length() - 1) == 'e') {
так мы в цикле мы же достоверно не можем узнать является ли 'e' или '-' последним символом результативной строки: например на вход "fff1fdf.asdsad3ewrt" 'e' не является последним символом входной строки, а в результативной "1.3е" последний

2023-03-26 14:37 UTC, shakirov-aa reviewed
13 из 14 тугриков

2023-03-26 14:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        for (int i = 0; i < tempArr.length; i++) {
Можно было заменить Arrays.fill ?

2023-03-26 14:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            while (left <= right) {
бинарный поиск лучше было вынести в отдельный метод, но ок

2023-03-26 14:37 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        int[] tempArr = new int[array.length];
тут можно было сделать массив count размером? и в итоге его вернуть потом

2023-03-26 14:39 UTC, closed without merging