Конопкин Евгений Домашка 2
polis-vk/java-tasks pull request #1231
Opened 2023-03-12 14:26 UTC by konopkin11

2023-03-14 21:43 UTC, shakirov-aa requested changes

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
можно эффективнее (не хуже O(K*logK + N))

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +
лишняя пустая строка

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
можно добавить досрочный выход, если очевидно, что лучшего варианта больше не найдём?

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +                    currentCharacter = new Pair<>(currentCharacter.first, currentCharacter.second + 1);
зачем каждый раз создавать объект? можно же не плодить лишние объекты

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        Pair<Character, Integer> currentCharacter = new Pair<>('0', 0);
надо в результат вернуть Pair, тут необязательно их создавать

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +
лишняя пустая строка

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str.isEmpty()) {
можно объединить с верхним if-ом

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else {
else можно не писать, в if-е выше был return

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            long value = Long.valueOf(result.toString());
parseLong?

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Character.isDigit(letter) || letter == '.' || letter == '-' || letter == 'e') {
тут явно можно уменьшить вложенность

2023-03-14 21:43 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Character.isDigit(letter) || letter == '.' || letter == '-' || letter == 'e') {
+ if-ы можно упростить в большинстве своём, местами добавить переход к следующей итерации (continue)

2023-03-18 10:58 UTC, shakirov-aa requested changes
Нет изменений, а старые замечания пометили как Resolved - дальше не стал смотреть :)

2023-03-18 10:58 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
можно за N * log(N)

2023-03-18 10:58 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            result[i] = array[i];
System.arraycopy

2023-03-18 10:58 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +
лишняя пустая строка

2023-03-20 15:47 UTC, shakirov-aa requested changes

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        quickSort(result, 0, result.length - 1);
Почему не отсортировать в самом начале?
Затем уже будем бинарным поиском искать минимальный и при добавлении делать сдвиг через System.arraycopy

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str == null || str.length() == 0) {
str.length() == 0 -> str.isEmpty()

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
тут можно добавить досрочный выход для кейса, когда очевидно, что лучшего варианта уже не найдём?

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        int eCount = 0;
тут можно boolean вместо int-ов. У нас же может быть всего одна точка и одна экспонента

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (eCount != 0) {
eCount != 0 || dotCount != 0 ?

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } catch (NumberFormatException e) {
Тут можно обойтись без catch exception.
Не очень строить бизнес логику на эксепшенах

2023-03-20 15:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (result == result.intValue()) {
эта проверка не понадобится, если дополнить if выше.
Тогда этот if уберём и просто в конце сделаем return result.intValue()

2023-03-22 11:15 UTC, konopkin11 commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        quickSort(result, 0, result.length - 1);
В задании указано, что нельзя сортировать входной массив и его копии

2023-03-26 14:41 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        quickSort(result, 0, result.length - 1);
> В задании указано, что нельзя сортировать входной массив и его копии

весь массив нельзя, да, но можно было скопировать первые count элементов, их отсортировать, затем бинарным поиском туда вставлять

2023-03-26 14:53 UTC, shakirov-aa reviewed
13 из 14 тугриков

2023-03-26 14:54 UTC, closed without merging