Davydov Nikita, 2hw
polis-vk/java-tasks pull request #1233
Opened 2023-03-12 20:11 UTC by nikdavkin

2023-03-14 10:31 UTC, VladislavFetisov requested changes

2023-03-14 10:31 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        return new Pair<>(symbol, max);
Отлично, полный балл

2023-03-18 09:29 UTC, VladislavFetisov requested changes

2023-03-18 09:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        PriorityQueue<Integer> maxNums = new PriorityQueue<>();
Попробуйте сделать то же самое, что делает PriorityQueue, но с массивом, то есть взять масстив размером count из исходного массива, и держать его отсортированным всегда, правильно выбирая место вставки для очередного элемента из исходного массива

2023-03-18 09:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                if (validString.length() == 0 ||
Молодец

2023-03-18 09:29 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                if (validString.length() == 0 ||
Полный балл

2023-03-19 15:34 UTC, nikdavkin commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        PriorityQueue<Integer> maxNums = new PriorityQueue<>();
Постарался исправить, но не уверен, что это хорошее решение, так как постоянно сдвигаем массив, что не есть хорошо. А понять должно ли входить это число в итоговый массив сразу мы не можем. Допустим, у нас должен быть массив длины 3, а элементы будут 1,2,3,4,5,6,7. Не могу придумать способа как ещё во время прохода понять, что нам подходят числа 5,6,7. Придётся каждый раз вставлять и сдвигать.

2023-03-20 19:23 UTC, VladislavFetisov requested changes

2023-03-20 19:23 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                    for (int j = i - 1; j >= 0; j--) {
первые count элементов можно отсортировать, прям вызвать Arrays.sort

2023-03-20 19:23 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                for (int j = count - 1; j >= 0; j--) {
Если у нас отсортированный массив, можем ли мы как-то умнее вставлять в него? От сдвига не избавиться в любом случае

2023-03-20 19:23 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                for (int j = count - 1; j >= 0; j--) {
умнее и быстрее

2023-03-26 20:52 UTC, VladislavFetisov approved these changes
14 тугриков

2023-03-26 20:52 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        if (array == null || count > array.length) {
хорошо, 4 тугрика

2023-03-26 20:53 UTC, closed without merging