Istaev Erdem/hw2
polis-vk/java-tasks pull request #1234
Opened 2023-03-12 22:41 UTC by Isterd

add homework 2

2023-03-14 17:36 UTC, VladislavFetisov requested changes

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        for (int i = 0; i < count; i++) {
Сложность должна быть минимум K*logK + N

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str == null || str.equals("")) {
у String есть метод isEmpty()

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        for (int i = 0; i < str.length(); i++) {
в таком случае лучше начинать с 1 индекса

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str == null || str.equals("")) {
то же самое

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        StringBuilder newStr = new StringBuilder();
я бы назвал filteredStr

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            return Integer.parseInt(newStr.toString());
тогда уже просто кастоните к инту, зачем опять парсить

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        char previousLetter = '.';
почему точка?

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        for (int i = 0; i < newStr.length(); i++) {
начинайте тогда с 1, если нужно смотреть на previous

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (newStr.charAt(indexLastLetter) == 'e') {
зачем это в цикле проверять?

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (newStr.charAt(indexLastLetter) == 'e') {
на таком тесте падать будет 1e1.0 (вылетает NumberFormatException), а по идее должен быть null

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (newStr.charAt(indexLastLetter) == 'e') {
Лучше все таки не хардкодить e в конец, а попробовать разделить и проверить, что может быть перед e и что после

2023-03-14 17:36 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Character.isDigit(previousLetter) && currentLetter == '-') {
а что после 'e' не может быть минуса?

2023-03-18 23:26 UTC, Isterd commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Character.isDigit(previousLetter) && currentLetter == '-') {
может. я тут проверяю на то что минус не может идти после цифры

2023-03-18 23:30 UTC, Isterd commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        char previousLetter = '.';
просто подумал с чего не может начинаться число. в принципе можно было любой символ написать с которого не начинается число

2023-03-20 19:40 UTC, VladislavFetisov requested changes

2023-03-20 19:40 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        if (count == 0) {
Попробуйте сделать то же самое, что делает PriorityQueue, но с массивом, то есть взять масстив размером count из исходного массива, и держать его отсортированным всегда, правильно выбирая место вставки для очередного элемента из исходного массива, например используя бинарный поиск

2023-03-20 19:40 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str.length() == 1) {
А так хорошо

2023-03-27 19:21 UTC, VladislavFetisov approved these changes

2023-03-27 19:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> -        return null;
считирил конечно, но ладно, 4 тугрика

2023-03-27 19:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str == null || str.isEmpty()) {
4 тугрика

2023-03-27 19:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str == null || str.isEmpty()) {
6 тугриков

2023-03-27 19:21 UTC, VladislavFetisov commented
14 тугриков

2023-03-27 19:23 UTC, closed without merging