First try
polis-vk/java-tasks pull request #1237
Opened 2023-03-13 16:44 UTC by NadirCianid

Романенко Денис

2023-03-14 17:46 UTC, VladislavFetisov requested changes

2023-03-14 17:46 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            for (int j = 0; j < temp.length; j++) {
Сложность должна быть максимум K*logK + N

2023-03-14 17:46 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        for (int i = 0; i < str.length(); i += currentCharCount) {
Очень сложно, можно за один цикл без вложенных все сделать

2023-03-14 17:46 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } catch (NumberFormatException e) {
Так нельзя делать, нужно все проверять в коде

2023-03-18 10:00 UTC, VladislavFetisov requested changes

2023-03-19 15:59 UTC, NadirCianid commented
Задание MaxTask пока не исправлял

2023-03-20 16:47 UTC, VladislavFetisov requested changes

2023-03-20 22:42 UTC, NadirCianid commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                        || ((temp.length() - 2 >= 0) && (temp.charAt(temp.length() - 2) == '-'))
именно на два символа назад проверяем, чтобы не было двух минусов подряд. (temp.charAt(temp.length() - 2) как раз предыдущий символ, а в данном месте текущий символ минус)

2023-03-23 16:56 UTC, NadirCianid commented
Я пропустил коммит с добавлением новых тестов в StringTask и исправил эту проблему сейчас.

2023-03-27 20:26 UTC, VladislavFetisov approved these changes
11 тугриков

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        if (array == null || count > array.length) return null;
почему не исправили?

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            return new int[]{};
можно int[0]

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +                array) {
это что вообще за форматирование

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +    public static void shift(int[] array, int newValue) {
получается не только шифт, но бинарный поиск

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
2 тугрика

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> -        return new Pair<>('s', 4);
4 тугрика

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            if (Long.parseLong(temp.toString()) <= Integer.MAX_VALUE && Long.parseLong(temp.toString()) >= Integer.MIN_VALUE) {
2 раза парсим методом лонга

2023-03-27 20:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
5 тугриков

2023-03-27 20:26 UTC, closed without merging