ДЗ 2
polis-vk/java-tasks pull request #1247
Opened 2023-03-15 21:22 UTC by zotic1001

Захаров. Не решил StringTask, икак не получается предусмотреть -1е-2 и т.д. Две другие решены, тесты проходитт

2023-03-18 11:26 UTC, shakirov-aa commented
Домашки с конифлктами не проверяются

<img width="940" alt="image" src="https://user-images.githubusercontent.com/47986788/226102338-fd281cc2-aa60-423e-a161-f6591341c3e4.png">

2023-03-18 11:29 UTC, shakirov-aa commented on src/test/java/ru/mail/polis/homework/simple/MainTest.java
> +}*/
+лишний файл в пулл реквесте

2023-03-18 14:55 UTC, zotic1001 commented
Вроде убрал конфликты

2023-03-20 17:05 UTC, shakirov-aa requested changes

2023-03-20 17:05 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            } else if (c == '.') {
тут и ниже можно без else if? переделать на обычный if, а в if-е выше добавить continue в конце

2023-03-20 17:05 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
Тут кажется более простым подход, когда в StringBuilder накапливаем числа.
Затем в конце уже с помощью методов обёрток возвращаем нужное значение в зависимости от того есть ли экспонента, точка, int или long

2023-03-26 15:20 UTC, shakirov-aa reviewed
MaxTask - 2 из 4
RepeatingCharacters - 4 из 4
StringTasks - 2 из 6

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        for (int i = 0; i < count; i++) {
тут сложность N^2 :(

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        //Если скопировать в result,
после // нужен пробел

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        // как выбирать без сортировки в тот же массив из которого выбираем, я не знаю
можно было скопировать первые count элементов в result, отсортировать result, затем в result вставлять при помощи бинарного поиска

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        for (; i < sb.length(); i++) {
1) Такие циклы сложнее понимать
2) Можно было за один проход по строке

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
не исправлено

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            } else {
else не нужен - можно просто return null

2023-03-26 15:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +                if (sb.charAt(i - 1) != 'e') {
можно схлопнуть с верхним if-ом?

2023-03-26 15:20 UTC, closed without merging