Nadezhda Gubenko
polis-vk/java-tasks pull request #1249
Opened 2023-03-16 00:09 UTC by nadezhdagub

Hometask 2: MaxTask, RepeatingCharacters, StringTasks

2023-03-18 11:27 UTC, shakirov-aa commented
Домашки с конфликтами не проверяются

<img width="906" alt="image" src="https://user-images.githubusercontent.com/47986788/226102396-c8c523e5-5784-493e-abae-004a0073b02b.png">

2023-03-20 17:18 UTC, shakirov-aa requested changes

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        else if (count == 0) return new int[0];
зачем else if? можно просто if

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        if (array == null || array.length < count) return null;
нет фигурных скобок, принято всегда писать

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
можно за O(N*log(N))

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            tmp[index] = Integer.MIN_VALUE;
Тут фактически поменяется значение исходного массива, а исходное значение нельзя менять

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str == "" || str == null) return null;
1. Лучше так: str == null || str.isEmpty()
2. Строки не сравнивают через ==
3. Нужны фигурные скобки

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        int maxEl = 1;
почему сам char не сохранить вместо индекса?

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
можно добавить досрочный выход, когда очевидно, что лучшего варианта уже не найдём?

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str == null || str.isEmpty()) return null;
фигурных скобок нет

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str.endsWith("-") || str.endsWith("e") || str.indexOf('.') != str.lastIndexOf('.') || str.indexOf('e') != str.lastIndexOf('e'))
фигурных скобок нет

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else if (Long.parseLong(res.toString()) <= Integer.MAX_VALUE
можно написать просто if вместо else if

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else if (Long.parseLong(res.toString()) <= Integer.MAX_VALUE
res.toString() лучше один раз где-то выше сделать

2023-03-20 17:18 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
В целом неплохо, но очень много ходим по символам строки.
Можно за один проход по строке сделать

2023-03-22 23:52 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        else if (count == 0) return new int[0];
исправила

2023-03-22 23:52 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +        if (array == null || array.length < count) return null;
исправила

2023-03-22 23:53 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
>      public static int[] getMaxArray(int[] array, int count) {
переписала код. теперь сложность алгоритма ниже

2023-03-22 23:53 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +        if (str == "" || str == null) return null;
исправила

2023-03-22 23:56 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
>      public static Pair<Character, Integer> getMaxRepeatingCharacters(String str) {
Можно, добавила

2023-03-22 23:56 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str == null || str.isEmpty()) return null;
исправила

2023-03-22 23:59 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str.endsWith("-") || str.endsWith("e") || str.indexOf('.') != str.lastIndexOf('.') || str.indexOf('e') != str.lastIndexOf('e'))
исправила

2023-03-22 23:59 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else if (Long.parseLong(res.toString()) <= Integer.MAX_VALUE
исправила

2023-03-22 23:59 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        } else if (Long.parseLong(res.toString()) <= Integer.MAX_VALUE
исправила

2023-03-22 23:59 UTC, nadezhdagub commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
>      public static Number valueOf(String str) {
переписала под один проход

2023-03-26 15:42 UTC, shakirov-aa reviewed
MaxTask - 4 из 4
RepeatingCharacters - 3 из 4
StringTasks - 4 из 6

Итого: 11 из 14

2023-03-26 15:42 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/MaxTask.java
> +            if (array[i] > res[0]) {
можно было вложенность уменьшить, но ок

2023-03-26 15:42 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/RepeatingCharacters.java
> +            if ((maxEl >= str.length() - i && str.charAt(i - 1) != str.charAt(i))
тут условие можно упростить

2023-03-26 15:42 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +        if (str.endsWith("-") || str.endsWith("e") || str.indexOf('.') != str.lastIndexOf('.') || str.indexOf('e') != str.lastIndexOf('e')) {
это всё можно было в цикле или после уже проверить? иначе это всё добавляет дополнительные проходы по строке (каждый такая операция это O(N) в худшем случае)

2023-03-26 15:42 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/objects/StringTasks.java
> +            return Integer.valueOf(toStr);
операцию парсинга можно было один раз вместо трёх?

2023-03-26 15:42 UTC, closed without merging