Homework3Done
polis-vk/java-tasks pull request #1280
Opened 2023-03-22 19:12 UTC by IgnatYuklyaevskiy

Юкляевский Игнат

2023-03-24 20:42 UTC, VladislavFetisov requested changes

2023-03-24 20:42 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +﻿package ru.mail.polis.homework.analyzer;public class NegativeTextAnalyzer {
это что вообще

2023-03-25 09:06 UTC, IgnatYuklyaevskiy commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +﻿package ru.mail.polis.homework.analyzer;public class NegativeTextAnalyzer {
Извините, я случайно видимо commit не сделал. Сейчас отправлю нормально

2023-03-28 06:53 UTC, VladislavFetisov requested changes

2023-03-28 06:53 UTC, VladislavFetisov commented on build.gradle
> +compileJava.options.encoding = 'UTF-8'
комитить это не нужно

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/FilterType.java
> +    private int priority;
final

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +        if (text == null) {
это можно вынести наверх, в метод Manager.analyze

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +                badSmiles) {
что за форматирование

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +                return FilterType.NEGATIVE_TEXT;
получается что ты здесь возвращаешь итоговое значение

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +        return FilterType.NEGATIVE_TEXT;
и здесь опять же возвращаешь его, странно получается

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TextFilterManager.java
> +            if (filter1.getFilterType().getPriority() < filter2.getFilterType().getPriority()) {
есть метод Integer.compare

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TextFilterManager.java
> +                filters) {
форматирование

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TextFilterManager.java
> +            if (textAnalyzer.analyzeText(text) != FilterType.GOOD) {
вот здесь как раз и получается странно, тебе уже analyzeText вернул значение, а ты еще getFilterTYpe вызываешь, получается при изменение логики придется менять в 2 местах, а можно в 1

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TooLongAnalyzer.java
> +    long maxLength;
модификаторы доступа

2023-03-28 06:53 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TooManyWordsAnalyzer.java
> +    int maxWords;
модификаторы доступа

2023-04-03 19:32 UTC, VladislavFetisov approved these changes
17 тугриков

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +                return FilterType.NEGATIVE_TEXT;
ну тогда уже возвращай getFilterType, или final переменную какую-нибудь

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/NegativeTextAnalyzer.java
> +                return FilterType.NEGATIVE_TEXT;
А то в 2х местах задавать придется

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/SpamAnalyzer.java
> +    private String[] badWords;
final

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TextFilterManager.java
> +        this.filters = filters;
стоило еще скопировать этот массив к себе

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TooLongAnalyzer.java
> +    private long maxLength;
final

2023-04-03 19:32 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/analyzer/TooManyWordsAnalyzer.java
> +    private int maxWords;
final

2023-04-03 19:34 UTC, closed without merging