nemchinov.ivan/hw4
polis-vk/java-tasks pull request #1321
Opened 2023-03-30 16:03 UTC by IvannMulion

2023-04-01 11:43 UTC, VladislavFetisov requested changes

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        if (value == null) return;
форматирование

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        valuesArray.sort((v1, v2) -> Integer.compare(getValuePopularity(v1), getValuePopularity(v2)));
получается если я вызову 10 раз итератор, то он 10 раз отсортирует, нельзя ли держать значения отсортированными уже? Чтобы вызов итератора был практически бесплатным

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        return mostPopularityValue;
mostPopular?

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        if (key == null) return;
форматирование

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +    private void addPopularityForKey(K key) {
это скорее incrementKeyPopularity

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        V lustValue = map.put(key, value);
![image](https://user-images.githubusercontent.com/55449507/229286640-28d0974d-9c2a-4a16-b44e-35a739044234.png)

2023-04-01 11:43 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        V lustValue = map.put(key, value);
скорее prevValue)

2023-04-01 12:38 UTC, IvannMulion commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        V lustValue = map.put(key, value);
)))))))

2023-04-01 13:21 UTC, IvannMulion commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        valuesArray.sort((v1, v2) -> Integer.compare(getValuePopularity(v1), getValuePopularity(v2)));
да, не продуманная реализация

немного подумав, пришел к такому решению
решил, что всегда держать значения отсортированными тоже не есть хорошая реализация, так как сортировка будет происходить всякий раз при работе ф-ии incrementValuePopularity(), которая вызывается достаточно часто

пришел к выводу, что проще будет сортировать уже финальный вариант массива при вызове итератора, если конечно это нужно

2023-04-03 19:05 UTC, VladislavFetisov requested changes

2023-04-03 19:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        if (!valuesArrayIsSorted) {
ну пересортировка не всегда работает за o(NlogN), в TreeMap например добавление очередного элемента и его сортировка происходит за logN

2023-04-03 19:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +    private void incrementKeyPopularity(K key) {
не кажется что для key и value реализации одинаковые?

2023-04-03 19:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +    private void incrementKeyPopularity(K key) {
может обьединить с помощью дженериков?

2023-04-03 19:05 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        if (!valuesArrayIsSorted) {
а сейчас фигня какая-то

2023-04-16 07:44 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/PopularMap.java
> +        if (!valuesArrayIsSorted) {
Не исправлено

2023-04-16 07:46 UTC, VladislavFetisov commented
8 из 10

2023-04-16 07:46 UTC, closed without merging