домашняя работа 5 Панфилов Фёдор
polis-vk/java-tasks pull request #1354
Opened 2023-04-06 14:26 UTC by iamboneidle

2023-04-08 09:21 UTC, VladislavFetisov requested changes

2023-04-08 09:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +    public final String recipient;
зачем тогда геттеры если public, или лучше не public?

2023-04-08 09:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +public class MailService<T extends Mail<T>> implements Consumer<T> {
зачем создавать рекурсивный дженерик, можно просто Mail<?>

2023-04-08 09:21 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +        Map<String, Integer> mapFreq = new HashMap<>();
нельзя создавать переменные, все с помощью стримов

2023-04-10 20:27 UTC, VladislavFetisov requested changes

2023-04-10 20:27 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public static <T extends Mail<T>> void process(MailService<T> service, List<T> mails) {
здесь то же

2023-04-10 20:27 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +//        Map<String, Integer> mapFreq = new HashMap<>();
ужас, такое нельзя оставлять

2023-04-10 20:27 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +                .sorted(Comparator.comparing(qtt -> (int) -qtt.getValue()))
можно было просто реализовать компаратор, а то это странно выглядит

2023-04-10 20:27 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +                .sorted(Comparator.comparing(qtt -> (int) -qtt.getValue()))
и тогда не нужно было бы 2 раза сортировать

2023-04-10 21:06 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public static <T extends Mail<T>> void process(MailService<T> service, List<T> mails) {
(рекурсивный дженерик)

2023-04-12 15:21 UTC, iamboneidle commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +//        Map<String, Integer> mapFreq = new HashMap<>();
ой, извините 😣

2023-04-16 08:06 UTC, VladislavFetisov commented
Отлично, полный балл

2023-04-16 08:06 UTC, closed without merging