Карасев Вячеслав, домашнее задание №5
polis-vk/java-tasks pull request #1357
Opened 2023-04-06 20:55 UTC by slavikfish03

2023-04-08 09:37 UTC, VladislavFetisov requested changes

2023-04-08 09:37 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +    private final String addressee;
можно просто receiver?

2023-04-08 09:37 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +        Map<String, Integer> popWords = new HashMap<>();
нельзя создавать переменные, все в стримах

2023-04-10 21:00 UTC, VladislavFetisov requested changes

2023-04-10 21:00 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +        return lines.flatMap(str -> Arrays.stream(str.toLowerCase().split("\\s*(\\s|,|!|\\.)\\s*"))).
так стримы никто не пишет, каждая функция=новая строчка

2023-04-11 14:58 UTC, slavikfish03 commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +        return lines.flatMap(str -> Arrays.stream(str.toLowerCase().split("\\s*(\\s|,|!|\\.)\\s*"))).
понял, принял, исправил

2023-04-16 08:20 UTC, VladislavFetisov commented
12 из 12

2023-04-16 08:20 UTC, closed without merging