siobko.boris/t5
polis-vk/java-tasks pull request #1358
Opened 2023-04-07 00:37 UTC by magellon17

2023-04-08 09:41 UTC, VladislavFetisov requested changes

2023-04-08 09:41 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +public class Mail<Ty> {
обычно просто T

2023-04-08 09:41 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +    private final Ty message;
скорее не message, а payload

2023-04-08 09:41 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    private final PopularMap<String, String> SendersAndRecipientsMap;
с маленькой буквы название

2023-04-08 09:41 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
>          return null;
тут же просто, почему не сделали?

2023-04-08 09:41 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/retake/first/PopularMap.java
>  public class PopularMap<K, V> implements Map<K, V> {
этого в данном pull request быть не должно

2023-04-08 10:15 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
>          return null;
Времени пока не было

2023-04-08 10:16 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/retake/first/PopularMap.java
>  public class PopularMap<K, V> implements Map<K, V> {
Мне заново писать то, что я писал в предыдущей работе ?

2023-04-08 10:17 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +public class Mail<Ty> {
Мне так привычней

2023-04-08 10:18 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    private final PopularMap<String, String> SendersAndRecipientsMap;
Понял

2023-04-10 21:02 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/Mail.java
> +public class Mail<Ty> {
не, нельзя

2023-04-10 21:04 UTC, VladislavFetisov requested changes

2023-04-10 21:04 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public static <Ty extends Mail<Ty>> void process(MailService<Ty> service, List<Ty> mails) {
MailService<Ty extends Mail<?>>

2023-04-10 21:04 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed().thenComparing(Map.Entry.comparingByKey()))
reversed-плохо

2023-04-11 14:15 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public static <Ty extends Mail<Ty>> void process(MailService<Ty> service, List<Ty> mails) {
Понял

2023-04-11 14:15 UTC, magellon17 commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed().thenComparing(Map.Entry.comparingByKey()))
Понял, исправлю

2023-04-16 08:22 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/collections/streams/WordFrequency.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed().thenComparing(Map.Entry.comparingByKey()))
не сдержал обещание получается

2023-04-16 08:24 UTC, VladislavFetisov commented
11 из 12

2023-04-16 08:24 UTC, closed without merging