pelipeychenko.denis/HW5
polis-vk/java-tasks pull request #1360
Opened 2023-04-07 20:52 UTC by LioShady

2023-04-08 07:19 UTC, shakirov-aa requested changes

2023-04-08 07:19 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public Map<String, List<T>> getMailBox() {
тут же получается мапа "отправитель -> все объекты, которые он отправил", а по условию получатель?

2023-04-08 07:19 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +        if (userMessagesMap.containsKey(mail.getSender())) {
этот else-if можно схлопнуть и сделать за одно обращение к мапе

2023-04-08 20:26 UTC, LioShady commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +    public Map<String, List<T>> getMailBox() {
Упс, исправил

2023-04-08 20:27 UTC, LioShady commented on src/main/java/ru/mail/polis/homework/collections/mail/MailService.java
> +        if (userMessagesMap.containsKey(mail.getSender())) {
переделал

2023-04-11 08:19 UTC, shakirov-aa commented
WordFrequency будет?

2023-04-15 08:18 UTC, shakirov-aa commented
7 из 12 тугриков, WordFrequency после дедлайна

2023-04-15 08:18 UTC, closed without merging