chupina.anna/hw6
polis-vk/java-tasks pull request #1393
Opened 2023-04-23 19:13 UTC by Aneynni

В разработке

2023-04-27 11:23 UTC, Aneynni commented
@VladislavFetisov извините, а третей проверки перед дедлайном уже не будет?

2023-04-30 18:20 UTC, VladislavFetisov commented
Так, дико извиняюсь, учеба убила, но я выжил, я сейчас проверю, и у вас еще будет 3 дня на исправление(как было бы за 3 дня до дедлайна)

2023-04-30 18:24 UTC, VladislavFetisov requested changes

2023-04-30 18:24 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/io/CopyFile.java
> +        try (InputStream is = Files.newInputStream(fileFrom)) {
есть у Files прекрасный метод Files.newBufferedReader()

2023-04-30 18:24 UTC, VladislavFetisov commented
Почти идеально

2023-05-01 12:35 UTC, Aneynni commented on src/main/java/ru/mail/polis/homework/io/CopyFile.java
> +        try (InputStream is = Files.newInputStream(fileFrom)) {
@VladislavFetisov принято. Прошу вас перенести мне дедлайн на день, 3 числа только смогу сесть за это, сейчас в поездке без ноута

2023-05-03 08:40 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/io/CopyFile.java
> +        try (InputStream is = Files.newInputStream(fileFrom)) {
ок

2023-05-04 16:26 UTC, VladislavFetisov commented on src/main/java/ru/mail/polis/homework/exception/Connection.java
> +        robot.setX(x);
лучше создать единый метод moveTO

2023-05-04 16:28 UTC, closed without merging