Kashirin Kirill HW7
polis-vk/java-tasks pull request #1401
Opened 2023-04-26 18:15 UTC by theusick

Каширин Кирилл

2023-04-27 10:15 UTC, shakirov-aa requested changes

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +            if (nonIgnoredField(objectClassField)) {
зачем эта доп проверка? ранее отфильтровали же

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +        StringBuilder fieldString = new StringBuilder();
Зачем создавать новый StringBuilder? Можно без него

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +        StringBuilder fieldString = new StringBuilder();
тоже лишний StringBuilder

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +        Object[] fieldValues = new Object[Array.getLength(fieldArray)];
Создаем массив, только чтобы потом у него вызвать .length ? Оч странно

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +                } catch (IllegalAccessException ignored) {}
форматирование

2023-04-27 10:15 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +                    .collect(Collectors.toList()));
тут на 123-125 форматирование съехало

2023-05-01 11:24 UTC, shakirov-aa requested changes

2023-05-01 11:24 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +            fieldValues[i] = Array.get(fieldArray, i);
Зачем пересохранять значения массива в новый массив и потом вызывать Arrays.toString ?
Нужно сразу в StringBuilder значения накапливать

2023-05-01 11:24 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +    private static String getObjectFieldString(Field field, Object object) throws IllegalAccessException {
Тут и в других методах возвращает String.
На самом деле нам не нужно плодить новые строки, а просто в один StringBuilder накапливать значения.
Этот StringBuilder соответственно передавать параметром в другие методы.
Ну и будут методы вроде "appendFieldToStringBuilder"

2023-05-01 11:24 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +        } else if (field.getType().isArray()) {
Тут не нужно писать else if.
В if-е выше был return, значит это можно просто отдельным if-ом

2023-05-02 10:03 UTC, theusick commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +        } else if (field.getType().isArray()) {
Оставил в данной реализации, тк метод теперь `void` и в if-else добавляет значение в стринг билдер, а не возвращает как раньше

2023-05-06 15:53 UTC, shakirov-aa reviewed
9 из 10

2023-05-06 15:53 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/homework/reflection/ReflectionToStringHelper.java
> +    private static void appendValueDelimiterToStringBuilder(StringBuilder stringBuilder) {
метод ради метода))

2023-05-06 15:53 UTC, closed without merging